#!/bin/bash

set -euE
shopt -s failglob

source "$(dirname "$0")/version.sh"

function git() {
  command git -c advice.detachedHead=false "$@"
}

UPSTREAM_VERSION=${1:?Please specify version}

OUTPUT_DIR=$(mktemp -d -p $(pwd) _orig_${UPSTREAM_VERSION}_XXXXXXXXXX)
trap 'rm -rf -- "$OUTPUT_DIR"' EXIT

echo '### cloning the latest and greatest debian release environment'
git clone --quiet --depth 1 $DEBIAN_REPO ${OUTPUT_DIR}/src

echo '### replace with own config'
rsync -a debian/ $OUTPUT_DIR/src/debian/

echo '### generating a debian conform orig file and install'
(
  cd ${OUTPUT_DIR}/src/
  PYTHONDONTWRITEBYTECODE=1 debian/bin/genorig.py --override-version $UPSTREAM_VERSION $UPSTREAM_REPO
)

echo '### importing orig via pristine-lfs'
pristine-lfs commit ${OUTPUT_DIR}/orig/*.orig.tar.xz
